### ISSUE TITLE
Launch page statistics and text are truncated

### ISSUE THREAD

**Issue by benpryke** [zoe/covid-tracker-react-native#857]
See the following images for clarity.

<img src="https://user-images.githubusercontent.com/1062063/97295834-be563f00-1847-11eb-91a6-3222c776b20f.png" width="300"> <img src="https://user-images.githubusercontent.com/1062063/97295888-d037e200-1847-11eb-8bcc-3cc5d8d750d2.png" width="300">

As you can see, the truncated statistics may be very misleading to an inexperienced user.

I assume this is to do with screen resolution, though I am not certain. I am using a OnePlus 6 for which the available screen size is approximately 412x790 px.

**Comment by selvach** [comment]
Thanks for reporting this. We have a fix in the works for this and will be releasing it soon. For the longest time, we weren't able to reproduce this - but it appears to be a problem to do with fort rendering on the OnePlus 6 devices only - due to the font weight chosen. 

The fix should be be pushed out in the next week or two!

**Comment by benpryke** [comment]
That was speedy, and sounds like a really obscure bug, you guys rock!

**Comment by selvach** [comment]
This has been rolled out to the Play Store!

**Comment by benpryke** [comment]
Looks perfect now, thank you @selvach and team!
